APP_NAME = "ProjectPlanner"
APP_AUTHOR = "Ethan Reynolds"

class defaultSettings:
    system_defaults = {
        "preserve_file": True,
        "saved_file_path": ""
    }
    defaults = {
        "file": None,
        "date_format": "YYYY-MM-DD",
        "time_format": "12h",
        "task_column_order": {
            "name" : 0,
            "type_" : 1,
            "group_" : 2,
            "category" : 3,
            "tags" : 4,
            "parent" : 5,
            "dependent_on" : 6,
            "sort_order" : 7,
            "level" : 8,
            "complete" : 9,
            "pct_complete" : 10,
            "hrs_estimate" : 11,
            "hrs_complete" : 12,
            "hrs_remaining" : 13,
            "hrs_scheduled" : 14,
            "hrs_logged" : 15,
            "start_date_scheduled" : 16,
            "end_date_scheduled" : 17,
            "duration_scheduled" : 18,
            "start_date_actual" : 19,
            "end_date_actual" : 20,
            "duration_actual" : 21,
            "due_date" : 22,
            "days_remaining" : 23,
            "status" : 24,
            "priority" : 25,
            "urgency" : 26,
            "archived" : 27,
            "date_archived" : 28,
            "date_created" : 29,
            "date_updated" : 30,
            "date_completed" : 31,
            "assigned_to" : 32,
            "created_by" : 33,
            "notes" : 34
        },
        "task_column_visible" : {
            "name" : True,
            "type_" : False,
            "group_" : False,
            "category" : False,
            "tags" : False,
            "parent" : False,
            "dependent_on" : False,
            "sort_order" : False,
            "level" : False,
            "complete" : True,
            "pct_complete" : True,
            "hrs_estimate" : True,
            "hrs_complete" : True,
            "hrs_remaining" : True,
            "hrs_scheduled" : True,
            "hrs_logged" : True,
            "start_date_scheduled" : True,
            "end_date_scheduled" : True,
            "duration_scheduled" : False,
            "start_date_actual" : False,
            "end_date_actual" : False,
            "duration_actual" : False,
            "due_date" : True,
            "days_remaining" : True,
            "status" : True,
            "priority" : True,
            "urgency" : False,
            "archived" : False,
            "date_archived" : False,
            "date_created" : False,
            "date_updated" : False,
            "date_completed" : False,
            "assigned_to" : False,
            "created_by" : False,
            "notes" : False
        },
        "task_column_width" : {
            "name" : 150,
            "type_" : 100,
            "group_" : 100,
            "category" : 100,
            "tags" : 100,
            "parent" : 100,
            "dependent_on" : 100,
            "sort_order" : 80,
            "level" : 80,
            "complete" : 20,
            "pct_complete" : 120,
            "hrs_estimate" : 120,
            "hrs_complete" : 120,
            "hrs_remaining" : 120,
            "hrs_scheduled" : 120,
            "hrs_logged" : 120,
            "start_date_scheduled" : 120,
            "end_date_scheduled" : 120,
            "duration_scheduled" : 120,
            "start_date_actual" : 120,
            "end_date_actual" : 120,
            "duration_actual" : 120,
            "due_date" : 120,
            "days_remaining" : 120,
            "status" : 100,
            "priority" : 100,
            "urgency" : 100,
            "archived" : 80,
            "date_archived" : 150,
            "date_created" : 150,
            "date_updated" : 150,
            "date_completed" : 150,
            "assigned_to" : 120,
            "created_by" : 120,
            "notes" : 200
        },
        "task_widget_column_order" : {
            "name" : 0,
            "type_" : 1,
            "group_" : 2,
            "category" : 3,
            "tags" : 4,
            "parent" : 5,
            "dependent_on" : 6,
            "sort_order" : 7,
            "level" : 8,
            "complete" : 9,
            "pct_complete" : 10,
            "hrs_estimate" : 11,
            "hrs_complete" : 12,
            "hrs_remaining" : 13,
            "hrs_scheduled" : 14,
            "hrs_logged" : 15,
            "start_date_scheduled" : 16,
            "end_date_scheduled" : 17,
            "duration_scheduled" : 18,
            "start_date_actual" : 19,
            "end_date_actual" : 20,
            "duration_actual" : 21,
            "due_date" : 22,
            "days_remaining" : 23,
            "status" : 24,
            "priority" : 25,
            "urgency" : 26,
            "archived" : 27,
            "date_archived" : 28,
            "date_created" : 29,
            "date_updated" : 30,
            "date_completed" : 31,
            "assigned_to" : 32,
            "created_by" : 33,
            "notes" : 34
        },  
        "task_widget_column_visible" :  {
            "name" : True,
            "type_" : False,
            "group_" : False,
            "category" : False,
            "tags" : False,
            "parent" : False,
            "dependent_on" : False,
            "sort_order" : False,
            "level" : False,
            "complete" : True,
            "pct_complete" : True,
            "hrs_estimate" : True,
            "hrs_complete" : True,
            "hrs_remaining" : True,
            "hrs_scheduled" : False,
            "hrs_logged" : False,
            "start_date_scheduled" : False,
            "end_date_scheduled" : False,
            "duration_scheduled" : False,
            "start_date_actual" : False,
            "end_date_actual" : False,
            "duration_actual" : False,
            "due_date" : True,
            "days_remaining" : False,
            "status" : True,
            "priority" : False,
            "urgency" : False,
            "archived" : False,
            "date_archived" : False,
            "date_created" : False,
            "date_updated" : False,
            "date_completed" : False,
            "assigned_to" : False,
            "created_by" : False,
            "notes" : False
        },
        "task_widget_column_width" : {
            "name" : 150,
            "type_" : 100,
            "group_" : 100,
            "category" : 100,
            "tags" : 100,
            "parent" : 100,
            "dependent_on" : 100,
            "sort_order" : 80,
            "level" : 80,
            "complete" : 80,
            "pct_complete" : 120,
            "hrs_estimate" : 120,
            "hrs_complete" : 120,
            "hrs_remaining" : 120,
            "hrs_scheduled" : 120,
            "hrs_logged" : 120,
            "start_date_scheduled" : 120,
            "end_date_scheduled" : 120,
            "duration_scheduled" : 120,
            "start_date_actual" : 120,
            "end_date_actual" : 120,
            "duration_actual" : 120,
            "due_date" : 120,
            "days_remaining" : 120,
            "status" : 100,
            "priority" : 100,
            "urgency" : 100,
            "archived" : 80,
            "date_archived" : 150,
            "date_created" : 150,
            "date_updated" : 150,
            "date_completed" : 150,
            "assigned_to" : 120,
            "created_by" : 120,
            "notes" : 200
        }
    }

class taskParameters:
    title = {
        "name" : "Name",
        "type_" : "Type",
        "group_" : "Group",
        "category" : "Category",
        "tags" : "Tags",
        "parent" : "Parent",
        "dependent_on" : "Dependent On",
        "sort_order" : "Sort Order",
        "level" : "Level",
        "complete" : "Complete",
        "pct_complete" : "Percent Complete",
        "hrs_estimate" : "Hours Estimate",
        "hrs_complete" : "Hours Complete",
        "hrs_remaining" : "Hours Remaining",
        "hrs_scheduled" : "Hours Scheduled",
        "hrs_logged" : "Hours Logged",
        "start_date_scheduled" : "Start Date Scheduled",
        "end_date_scheduled" : "End Date Scheduled",
        "duration_scheduled" : "Duration Scheduled",
        "start_date_actual" : "Start Date Actual",
        "end_date_actual" : "End Date Actual",
        "duration_actual" : "Duration Actual",
        "due_date" : "Due Date",
        "days_remaining" : "Days Remaining",
        "status" : "Status",
        "priority" : "Priority",
        "urgency" : "Urgency",
        "archived" : "Archived",
        "date_archived" : "Date Archived",
        "date_created" : "Date Created",
        "date_updated" : "Date Updated",
        "date_completed" : "Date Completed",
        "assigned_to" : "Assigned To",
        "created_by" : "Created By",
        "notes" : "Notes"
    }        

    key = {
        "Name": "name",
        "Type": "type_",
        "Group": "group_",
        "Category": "category",
        "Tags": "tags",
        "Parent": "parent",
        "Dependent On": "dependent_on",
        "Sort Order": "sort_order",
        "Level": "level",
        "Complete": "complete",
        "Percent Complete": "pct_complete",
        "Hours Estimate": "hrs_estimate",
        "Hours Complete": "hrs_complete",
        "Hours Remaining": "hrs_remaining",
        "Hours Scheduled": "hrs_scheduled",
        "Hours Logged": "hrs_logged",
        "Start Date Scheduled": "start_date_scheduled",
        "End Date Scheduled": "end_date_scheduled",
        "Duration Scheduled": "duration_scheduled",
        "Start Date Actual": "start_date_actual",
        "End Date Actual": "end_date_actual",
        "Duration Actual": "duration_actual",
        "Due Date": "due_date",
        "Days Remaining": "days_remaining",
        "Status": "status",
        "Priority": "priority",
        "Urgency": "urgency",
        "Archived": "archived",
        "Date Archived": "date_archived",
        "Date Created": "date_created",
        "Date Updated": "date_updated",
        "Date Completed": "date_completed",
        "Assigned To": "assigned_to",
        "Created By": "created_by",
        "Notes": "notes"
    }